version: "3.3"
services:
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - './dockervolume/mongodb:/data/db'
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports: 
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
    data: {}
